baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
    api_url = "http://localhost:8055"

[markup.goldmark.renderer]
  unsafe = true

[module]
  [[module.mounts]]
    source = "content"
    target = "content"

  [[module.mounts]]
    source = "prebuild/public/content"
    target = "content"
